name: Build and push build-env image

on: workflow_dispatch

jobs:
  main:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker/build-env/.
          tags: ghcr.io/a-w50/gh-actions/build-env:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

