name: Dockerfile push test

on: workflow_dispatch

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: docker/linter/.
          tags: ghcr.io/a-w50/gh-actions/blabla:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

